version : '3.9'

services:
  db:
    image: postgres:15
    container_name: enterprise_db
    restart : always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_db: agentic_db
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: agentic_app
    ports:
      - "8000:8000"
    depends_on:
      - db